version: "3"

services:
  mysql:
    image: percona/percona-server:8.0
    environment:
	    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password 
    ports:
      - "3306:3306"
	  volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db-password
      
  application:
    image: dockersamples/static-site:latest  ##Just sample name given
    environment:
      PGUSER: pspdfkit
      PGPASSWORD: password
    depends_on:
      - mysql
    expose:
      - "3000"
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application
    ports:
      - "80:80"

volumes:
  db-data:
  
secrets:
  db-password:
    file: db/password.txt
